# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c472b1c8d7d12e4199fa0d77cc280f4fb0b9d71855b64b42a5a41c141bb9249789f7d785282182cf9322fae2bab37cc547ee5f12e8474c9f232fcc342a3c74

test:
  secret_key_base: 6677f22acda114084be472e8b3700efafcc237591b9d7d2f8fc32b6c120c5328a0924c529cfa5ff0943755d41a559704eeaa2ca85c953c3692677c5d6a62bdbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
